### ISSUE TITLE
CMD with sudo squashes any environment variables you pass in....

### ISSUE THREAD

**Issue by fgauer** [jsreport/docker#1]
If you want to pass in an environment variable using the docker run -e option, running the server command with sudo squashes any environment variable you pass in:

sudo NODE_ENV=${NODE_ENV:-production} node "/home/jsreport/server.js" --httpsPort=2945

...so something like this does not work: docker run -e SOME_ENV_VARIABLE="MYVALUE" -p 443:2945 jsreport/jsreport

If you leave the sudo off, it works: node "/home/jsreport/server.js" --httpsPort=2945 

We run our docker comments passing in environment variables, so this took us awhile to figure out. I just thought I'd pass the information along. Thanks!

**Comment by pofider** [comment]
Thank you. I'll try to remove sudo and check what it does.

**Comment by pofider** [comment]
I've removed the sudo now as suggested and it really works well. Thank you.
